version: "3"
services:
  db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=plz
      - POSTGRES_USER=plz
      - POSTGRES_DB=plz
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - 5432:5432
    networks:
      - backend

networks:
  backend:
